/*
 * Copyright (C) 2014-2026 Philip Helger (www.helger.com)
 * philip[at]helger[dot]com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.helger.graph.impl;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import com.helger.graph.IMutableGraphNode;
import com.helger.unittest.support.TestHelper;

/**
 * Test class for class {@link GraphRelationFast}.
 *
 * @author Philip Helger
 */
public final class GraphRelationFastTest
{
  @Test
  public void testAutoGeneratedID ()
  {
    final IMutableGraphNode aFrom = new GraphNode ("from");
    final IMutableGraphNode aTo = new GraphNode ("to");

    final GraphRelationFast aRel = new GraphRelationFast (aFrom, aTo);
    assertNotNull (aRel.getID ());
    assertTrue (aRel.isRelatedTo (aFrom));
    assertTrue (aRel.isRelatedTo (aTo));
    assertNotNull (aRel.toString ());

    // Equality is based on the ID only
    assertEquals (aRel, aRel);
    assertEquals (aRel.hashCode (), aRel.hashCode ());
    assertFalse (aRel.equals (null));
    assertFalse (aRel.equals ("any other type"));
    assertFalse (aRel.equals (new GraphRelationFast (aFrom, aTo)));
  }

  @Test
  public void testExplicitID ()
  {
    final IMutableGraphNode aFrom = new GraphNode ("from");
    final IMutableGraphNode aTo = new GraphNode ("to");

    final GraphRelationFast aRel = new GraphRelationFast ("id1", aFrom, aTo);
    assertEquals ("id1", aRel.getID ());

    // Same ID means equal, even for different nodes
    TestHelper.testDefaultImplementationWithEqualContentObject (aRel,
                                                                new GraphRelationFast ("id1",
                                                                                       new GraphNode ("other"),
                                                                                       new GraphNode ("other2")));
    TestHelper.testDefaultImplementationWithDifferentContentObject (aRel, new GraphRelationFast ("id2", aFrom, aTo));
  }
}
