/*
 * Copyright (C) 2014-2026 Philip Helger (www.helger.com)
 * philip[at]helger[dot]com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.helger.collection.helper;

import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

import com.helger.annotation.style.ReturnsMutableCopy;
import com.helger.collection.commons.CommonsArrayList;
import com.helger.collection.commons.CommonsHashSet;
import com.helger.collection.commons.CommonsLinkedHashSet;
import com.helger.collection.commons.CommonsTreeSet;
import com.helger.collection.stack.NonBlockingStack;

/**
 * Collection helper for primitive data types (boolean, byte, char, double, float, int, long and
 * short).
 *
 * @author Philip Helger
 */
public final class PrimitiveCollectionHelper
{
  private PrimitiveCollectionHelper ()
  {}

  // The code below is generated by MainCreateCollectionHelperCode

  @NonNull
  @ReturnsMutableCopy
  public static CommonsArrayList <Boolean> createPrimitiveList (final boolean @Nullable... aValues)
  {
    final CommonsArrayList <Boolean> ret = new CommonsArrayList <> ();
    if (aValues != null)
      for (final boolean aValue : aValues)
        ret.add (Boolean.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsArrayList <Byte> createPrimitiveList (final byte @Nullable... aValues)
  {
    final CommonsArrayList <Byte> ret = new CommonsArrayList <> ();
    if (aValues != null)
      for (final byte aValue : aValues)
        ret.add (Byte.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsArrayList <Character> createPrimitiveList (final char @Nullable... aValues)
  {
    final CommonsArrayList <Character> ret = new CommonsArrayList <> ();
    if (aValues != null)
      for (final char aValue : aValues)
        ret.add (Character.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsArrayList <Double> createPrimitiveList (final double @Nullable... aValues)
  {
    final CommonsArrayList <Double> ret = new CommonsArrayList <> ();
    if (aValues != null)
      for (final double aValue : aValues)
        ret.add (Double.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsArrayList <Float> createPrimitiveList (final float @Nullable... aValues)
  {
    final CommonsArrayList <Float> ret = new CommonsArrayList <> ();
    if (aValues != null)
      for (final float aValue : aValues)
        ret.add (Float.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsArrayList <Integer> createPrimitiveList (final int @Nullable... aValues)
  {
    final CommonsArrayList <Integer> ret = new CommonsArrayList <> ();
    if (aValues != null)
      for (final int aValue : aValues)
        ret.add (Integer.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsArrayList <Long> createPrimitiveList (final long @Nullable... aValues)
  {
    final CommonsArrayList <Long> ret = new CommonsArrayList <> ();
    if (aValues != null)
      for (final long aValue : aValues)
        ret.add (Long.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsArrayList <Short> createPrimitiveList (final short @Nullable... aValues)
  {
    final CommonsArrayList <Short> ret = new CommonsArrayList <> ();
    if (aValues != null)
      for (final short aValue : aValues)
        ret.add (Short.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsHashSet <Boolean> createPrimitiveSet (final boolean @Nullable... aValues)
  {
    final CommonsHashSet <Boolean> ret = new CommonsHashSet <> ();
    if (aValues != null)
      for (final boolean aValue : aValues)
        ret.add (Boolean.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsHashSet <Byte> createPrimitiveSet (final byte @Nullable... aValues)
  {
    final CommonsHashSet <Byte> ret = new CommonsHashSet <> ();
    if (aValues != null)
      for (final byte aValue : aValues)
        ret.add (Byte.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsHashSet <Character> createPrimitiveSet (final char @Nullable... aValues)
  {
    final CommonsHashSet <Character> ret = new CommonsHashSet <> ();
    if (aValues != null)
      for (final char aValue : aValues)
        ret.add (Character.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsHashSet <Double> createPrimitiveSet (final double @Nullable... aValues)
  {
    final CommonsHashSet <Double> ret = new CommonsHashSet <> ();
    if (aValues != null)
      for (final double aValue : aValues)
        ret.add (Double.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsHashSet <Float> createPrimitiveSet (final float @Nullable... aValues)
  {
    final CommonsHashSet <Float> ret = new CommonsHashSet <> ();
    if (aValues != null)
      for (final float aValue : aValues)
        ret.add (Float.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsHashSet <Integer> createPrimitiveSet (final int @Nullable... aValues)
  {
    final CommonsHashSet <Integer> ret = new CommonsHashSet <> ();
    if (aValues != null)
      for (final int aValue : aValues)
        ret.add (Integer.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsHashSet <Long> createPrimitiveSet (final long @Nullable... aValues)
  {
    final CommonsHashSet <Long> ret = new CommonsHashSet <> ();
    if (aValues != null)
      for (final long aValue : aValues)
        ret.add (Long.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsHashSet <Short> createPrimitiveSet (final short @Nullable... aValues)
  {
    final CommonsHashSet <Short> ret = new CommonsHashSet <> ();
    if (aValues != null)
      for (final short aValue : aValues)
        ret.add (Short.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsLinkedHashSet <Boolean> createPrimitiveOrderedSet (final boolean @Nullable... aValues)
  {
    final CommonsLinkedHashSet <Boolean> ret = new CommonsLinkedHashSet <> ();
    if (aValues != null)
      for (final boolean aValue : aValues)
        ret.add (Boolean.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsLinkedHashSet <Byte> createPrimitiveOrderedSet (final byte @Nullable... aValues)
  {
    final CommonsLinkedHashSet <Byte> ret = new CommonsLinkedHashSet <> ();
    if (aValues != null)
      for (final byte aValue : aValues)
        ret.add (Byte.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsLinkedHashSet <Character> createPrimitiveOrderedSet (final char @Nullable... aValues)
  {
    final CommonsLinkedHashSet <Character> ret = new CommonsLinkedHashSet <> ();
    if (aValues != null)
      for (final char aValue : aValues)
        ret.add (Character.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsLinkedHashSet <Double> createPrimitiveOrderedSet (final double @Nullable... aValues)
  {
    final CommonsLinkedHashSet <Double> ret = new CommonsLinkedHashSet <> ();
    if (aValues != null)
      for (final double aValue : aValues)
        ret.add (Double.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsLinkedHashSet <Float> createPrimitiveOrderedSet (final float @Nullable... aValues)
  {
    final CommonsLinkedHashSet <Float> ret = new CommonsLinkedHashSet <> ();
    if (aValues != null)
      for (final float aValue : aValues)
        ret.add (Float.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsLinkedHashSet <Integer> createPrimitiveOrderedSet (final int @Nullable... aValues)
  {
    final CommonsLinkedHashSet <Integer> ret = new CommonsLinkedHashSet <> ();
    if (aValues != null)
      for (final int aValue : aValues)
        ret.add (Integer.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsLinkedHashSet <Long> createPrimitiveOrderedSet (final long @Nullable... aValues)
  {
    final CommonsLinkedHashSet <Long> ret = new CommonsLinkedHashSet <> ();
    if (aValues != null)
      for (final long aValue : aValues)
        ret.add (Long.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsLinkedHashSet <Short> createPrimitiveOrderedSet (final short @Nullable... aValues)
  {
    final CommonsLinkedHashSet <Short> ret = new CommonsLinkedHashSet <> ();
    if (aValues != null)
      for (final short aValue : aValues)
        ret.add (Short.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsTreeSet <Boolean> createPrimitiveSortedSet (final boolean @Nullable... aValues)
  {
    final CommonsTreeSet <Boolean> ret = new CommonsTreeSet <> ();
    if (aValues != null)
      for (final boolean aValue : aValues)
        ret.add (Boolean.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsTreeSet <Byte> createPrimitiveSortedSet (final byte @Nullable... aValues)
  {
    final CommonsTreeSet <Byte> ret = new CommonsTreeSet <> ();
    if (aValues != null)
      for (final byte aValue : aValues)
        ret.add (Byte.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsTreeSet <Character> createPrimitiveSortedSet (final char @Nullable... aValues)
  {
    final CommonsTreeSet <Character> ret = new CommonsTreeSet <> ();
    if (aValues != null)
      for (final char aValue : aValues)
        ret.add (Character.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsTreeSet <Double> createPrimitiveSortedSet (final double @Nullable... aValues)
  {
    final CommonsTreeSet <Double> ret = new CommonsTreeSet <> ();
    if (aValues != null)
      for (final double aValue : aValues)
        ret.add (Double.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsTreeSet <Float> createPrimitiveSortedSet (final float @Nullable... aValues)
  {
    final CommonsTreeSet <Float> ret = new CommonsTreeSet <> ();
    if (aValues != null)
      for (final float aValue : aValues)
        ret.add (Float.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsTreeSet <Integer> createPrimitiveSortedSet (final int @Nullable... aValues)
  {
    final CommonsTreeSet <Integer> ret = new CommonsTreeSet <> ();
    if (aValues != null)
      for (final int aValue : aValues)
        ret.add (Integer.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsTreeSet <Long> createPrimitiveSortedSet (final long @Nullable... aValues)
  {
    final CommonsTreeSet <Long> ret = new CommonsTreeSet <> ();
    if (aValues != null)
      for (final long aValue : aValues)
        ret.add (Long.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static CommonsTreeSet <Short> createPrimitiveSortedSet (final short @Nullable... aValues)
  {
    final CommonsTreeSet <Short> ret = new CommonsTreeSet <> ();
    if (aValues != null)
      for (final short aValue : aValues)
        ret.add (Short.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static NonBlockingStack <Boolean> createPrimitiveStack (final boolean @Nullable... aValues)
  {
    final NonBlockingStack <Boolean> ret = new NonBlockingStack <> ();
    if (aValues != null)
      for (final boolean aValue : aValues)
        ret.add (Boolean.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static NonBlockingStack <Byte> createPrimitiveStack (final byte @Nullable... aValues)
  {
    final NonBlockingStack <Byte> ret = new NonBlockingStack <> ();
    if (aValues != null)
      for (final byte aValue : aValues)
        ret.add (Byte.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static NonBlockingStack <Character> createPrimitiveStack (final char @Nullable... aValues)
  {
    final NonBlockingStack <Character> ret = new NonBlockingStack <> ();
    if (aValues != null)
      for (final char aValue : aValues)
        ret.add (Character.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static NonBlockingStack <Double> createPrimitiveStack (final double @Nullable... aValues)
  {
    final NonBlockingStack <Double> ret = new NonBlockingStack <> ();
    if (aValues != null)
      for (final double aValue : aValues)
        ret.add (Double.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static NonBlockingStack <Float> createPrimitiveStack (final float @Nullable... aValues)
  {
    final NonBlockingStack <Float> ret = new NonBlockingStack <> ();
    if (aValues != null)
      for (final float aValue : aValues)
        ret.add (Float.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static NonBlockingStack <Integer> createPrimitiveStack (final int @Nullable... aValues)
  {
    final NonBlockingStack <Integer> ret = new NonBlockingStack <> ();
    if (aValues != null)
      for (final int aValue : aValues)
        ret.add (Integer.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static NonBlockingStack <Long> createPrimitiveStack (final long @Nullable... aValues)
  {
    final NonBlockingStack <Long> ret = new NonBlockingStack <> ();
    if (aValues != null)
      for (final long aValue : aValues)
        ret.add (Long.valueOf (aValue));
    return ret;
  }

  @NonNull
  @ReturnsMutableCopy
  public static NonBlockingStack <Short> createPrimitiveStack (final short @Nullable... aValues)
  {
    final NonBlockingStack <Short> ret = new NonBlockingStack <> ();
    if (aValues != null)
      for (final short aValue : aValues)
        ret.add (Short.valueOf (aValue));
    return ret;
  }
}
