/*
 * Copyright (C) 2014-2025 Philip Helger (www.helger.com)
 * philip[at]helger[dot]com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.helger.jaxb.adapter;

import java.util.List;

import com.helger.annotation.concurrent.Immutable;
import com.helger.annotation.style.UsedInGeneratedCode;
import com.helger.base.clone.CloneHelper;
import com.helger.base.equals.EqualsHelper;
import com.helger.base.hashcode.HashCodeCalculator;
import com.helger.base.hashcode.HashCodeGenerator;

import jakarta.annotation.Nullable;
import jakarta.xml.bind.JAXBElement;

/**
 * Misc utility classes for JAXB
 *
 * @author Philip Helger
 * @since 9.2.0
 */
@Immutable
public final class JAXBHelper
{
  private JAXBHelper ()
  {}

  /**
   * Check if two JAXB elements are identical.<br>
   * This method is used in the code generated by the ph-jaxb-plugin!
   *
   * @param aObj1
   *        First object. May be <code>null</code>.
   * @param aObj2
   *        Second object. May be <code>null</code>.
   * @return <code>true</code> if they are equal.
   * @since v12.0.0
   */
  @UsedInGeneratedCode
  public static boolean equalsJAXBElements (@Nullable final JAXBElement <?> aObj1,
                                            @Nullable final JAXBElement <?> aObj2)
  {
    if (EqualsHelper.identityEqual (aObj1, aObj2))
      return true;
    if (aObj1 == null || aObj2 == null)
      return false;
    return EqualsHelper.equals (aObj1.getDeclaredType (), aObj2.getDeclaredType ()) &&
           EqualsHelper.equals (aObj1.getName (), aObj2.getName ()) &&
           EqualsHelper.equals (aObj1.getScope (), aObj2.getScope ()) &&
           EqualsHelper.equals (aObj1.isNil (), aObj2.isNil ()) &&
           EqualsHelper.equals (aObj1.getValue (), aObj2.getValue ());
  }

  /**
   * Check if two lists of JAXB elements are identical.<br>
   * This method is used in the code generated by the ph-jaxb-plugin!
   *
   * @param aObj1
   *        First list. May be <code>null</code>.
   * @param aObj2
   *        Second list. May be <code>null</code>.
   * @return <code>true</code> if they are equal.
   * @since v12.0.0 RC2
   */
  @UsedInGeneratedCode
  public static boolean equalsJAXBElementLists (@Nullable final List <JAXBElement <?>> aObj1,
                                                @Nullable final List <JAXBElement <?>> aObj2)
  {
    if (EqualsHelper.identityEqual (aObj1, aObj2))
      return true;

    if (aObj1 == null || aObj2 == null)
      return false;

    final int nLen = aObj1.size ();
    if (nLen != aObj2.size ())
      return false;
    for (int i = 0; i < nLen; ++i)
      if (!equalsJAXBElements (aObj1.get (i), aObj2.get (i)))
        return false;
    return true;
  }

  /**
   * Get the hashcode of a JAXBElement.<br>
   * This method is used in the code generated by the ph-jaxb-plugin!
   *
   * @param aObj
   *        JAXBElement to get the hashcode from. May be <code>null</code>.
   * @return the hashcode
   * @since v12.0.0
   */
  @UsedInGeneratedCode
  public static int getHashcode (@Nullable final JAXBElement <?> aObj)
  {
    if (aObj == null)
      return HashCodeCalculator.HASHCODE_NULL;

    return new HashCodeGenerator (aObj.getClass ()).append (aObj.getDeclaredType ())
                                                   .append (aObj.getName ())
                                                   .append (aObj.getScope ())
                                                   .append (aObj.isNil ())
                                                   .append (aObj.getValue ())
                                                   .getHashCode ();
  }

  @Nullable
  public static <DATATYPE> JAXBElement <DATATYPE> getClonedJAXBElement (@Nullable final JAXBElement <DATATYPE> aObj)
  {
    if (aObj == null)
      return null;

    final DATATYPE aClonedValue = CloneHelper.getClonedValue (aObj.getValue ());
    final JAXBElement <DATATYPE> ret = new JAXBElement <> (aObj.getName (),
                                                           aObj.getDeclaredType (),
                                                           aObj.getScope (),
                                                           aClonedValue);
    ret.setNil (aObj.isNil ());
    return ret;
  }
}
